spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jam/tutorial/spring/medium_clone
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
