spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jam/tutorial/spring/medium_clone
    username: sa
    password:
    driver-class-name: org.h2.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
